sudo: false
language: python
python:
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - 'nightly'
install:
  - pip install tox-travis
  - pip install .
script:
  - tox
after_success:
  - codecov
